EventsEngineering/EventsEngineering/Controllers/EventDataController.cs
using EventsEngineering.DTO;
using EventsEngineering.Manager;
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace EventsEngineering.Controllers
{
    public class EventDataController : Controller
    {
        EventDataManager eventmanager = new EventDataManager();
        // GET: EventData
        public ActionResult Index()
        {
            List<EventData> eventList = eventmanager.RetrieveEvents();
            //EventData data = null;
            // data.Links = new Dictionary<string, string>();
            return View(eventList);
        }

        // GET: EventDAta/Details/5
        public ActionResult Details(int Id)
        {
            var eventdata = eventmanager.RetrieveEvent(Id);
            return View("~/Views/EventData/Details.cshtml", eventdata);
        }

        // GET: EventData/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: EventData/Create
        [HttpPost]
        public ActionResult Create(EventData eve)
        {
            try
            {
                eve.VenueImage = "venue_" + eve.EventName + ".jpg";
                eve.VenueLocationImage = "location_" + eve.EventName + ".jpg";
                eve.EventImage = eve.EventName + ".jpg";
                int retVal = eventmanager.InsertEvent(eve);
                if (retVal == 1)
                {
                    //TODO: Upload the file to server

                    HttpPostedFileBase baseFile = Request.Files[0];
                    HttpPostedFileBase baseFile1 = Request.Files[1];
                    HttpPostedFileBase baseFile2 = Request.Files[2];
                    var path = Path.Combine(Server.MapPath(@"\images"), eve.VenueImage);
                    var path1 = Path.Combine(Server.MapPath(@"\images"), eve.VenueLocationImage);
                    var path2 = Path.Combine(Server.MapPath(@"\images"), eve.EventImage);
                    baseFile.SaveAs(path);
                    baseFile1.SaveAs(path1);
                    baseFile2.SaveAs(path2);
                }
                return RedirectToAction("Index");
            }
            catch (Exception ex)
            {
                return View();
            }
        }

        // GET: EventData/Edit/5
        public ActionResult Edit(int id)
        {
            var eve = eventmanager.Get(id);
            //var path = Path.Combine(@"..\..\images", eve.VenueImage);
            //eve.VenueImage = path;
            //var path1 = Path.Combine(@"..\..\images", eve.VenueImage);
            //eve.VenueLocationImage = path;
            //var path2 = Path.Combine(@"..\..\images", eve.AddImage);
            //eve.AddImage = path;
            return View("Edit", eve);
        }

        // POST: EventData/Edit/5
        [HttpPost]
        public ActionResult Edit(int id, EventData eve)
        {
            try
            {

                eventmanager.UpdateEvent(eve);
                return RedirectToAction("Index");
            }
            catch
            {
                return View();
            }
        }

        // GET: EventData/Delete/5
        public ActionResult Delete(int id)
        {
            var eve = eventmanager.Get(id);
            return View("Delete", eve);
        }

        // POST: EventData/Delete/5
        [HttpPost]
        public ActionResult Delete(int id, FormCollection collection)
        {
            try
            {
                // TODO: Add delete logic here
                eventmanager.DeleteEvent(id);
                return RedirectToAction("Index");
            }
            catch
            {
                return View();
            }
        }
    }
}

EventsEngineering/EventsEngineering/Views/EventData/Create.cshtml
@model EventsEngineering.DTO.EventData

@{
    ViewBag.Title = "Create";
}

<h2>Add an Event</h2>

@using (Html.BeginForm("Create","EventData", FormMethod.Post, new { enctype = "multipart/form-data" }))
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        @*<div class="col-lg-6">*@
            <h4>EventData</h4>
            <hr />
            @*@Html.ValidationSummary(true, "", new { @class = "text-danger" })*@
            <div class="form-group">
                @Html.LabelFor(x => x.EventName, "Event Name :", htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.EventName, new { htmlAttributes = new { @class = "form-control", placeholder = "Event Name" } })
                    @Html.ValidationMessageFor(model => model.EventName, "", new { @class = "text-danger" })
                </div>
            </div>

            <div class="form-group">
                @Html.LabelFor(x => x.EventDescription, "Event Description :", htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.TextAreaFor(model => model.EventDescription, 5, 50, null)
                    @*@Html.EditorFor(model => model.EventDescription, new { htmlAttributes = new { @class = "form-control" } })*@
                    @Html.ValidationMessageFor(model => model.EventDescription, "", new { @class = "text-danger" })
                </div>
            </div>

            <div class="form-group">
                @Html.LabelFor(x => x.EventDate, "Event Date :", htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.EventDate, new { htmlAttributes = new { @class = "form-control", placeholder = "Event Date" } })
                    @Html.ValidationMessageFor(model => model.EventDate, "", new { @class = "text-danger" })
                </div>
            </div>

            <div class="form-group">
                @Html.LabelFor(x => x.Venue, "Venue :", htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.TextAreaFor(model => model.Venue, 5, 50, null)
                    @*@Html.EditorFor(model => model.Venue, new { htmlAttributes = new { @class = "form-control" } })*@
                    @Html.ValidationMessageFor(model => model.Venue, "", new { @class = "text-danger" })
                </div>
            </div>

            <div class="form-group">
                @Html.LabelFor(x => x.VenueURL, "Venue URL :", htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.VenueURL, new { htmlAttributes = new { @class = "form-control", placeholder = "Venue URL" } })
                    @Html.ValidationMessageFor(model => model.VenueURL, "", new { @class = "text-danger" })
                </div>
            </div>

            <div class="form-group">
                @Html.LabelFor(x => x.VenueImage, "Venue Image :", htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @*@Html.EditorFor(model => model.VenueImage, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.VenueImage, "", new { @class = "text-danger" })*@
                    @*<label for="file">Upload Venue Image:</label>*@
                    <input type="file" name="file" style="width: 100%;" />
                </div>
            </div>

            <div class="form-group">
                @Html.LabelFor(x => x.VenueLocationImage, "Venue Location Image :", htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @*@Html.EditorFor(model => model.VenueLocationImage, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.VenueLocationImage, "", new { @class = "text-danger" })*@
                    @*<label for="file">Upload Venue Location Image:</label>*@
                    <input type="file" name="file" id="file" style="width: 100%;" />
                </div>
            </div>
        
            
                <div class="form-group">
                    @Html.LabelFor(x => x.EventImage, "Image :", htmlAttributes: new { @class = "control-label col-md-2" })
                    <div class="col-md-10">
                        @*@Html.EditorFor(model => model.EventImage, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.EventImage, "", new { @class = "text-danger" })*@
                        @*<label for="file">Upload Event Image:</label>*@
                        <input type="file" name="file" id="file" style="width: 100%;" />
                    </div>
                </div>

                <div class="form-group">
                    @Html.LabelFor(x => x.EventImageTooltip, "Image Tooltip :", htmlAttributes: new { @class = "control-label col-md-2" })
                    <div class="col-md-10">
                        @Html.EditorFor(model => model.EventImageTooltip, new { htmlAttributes = new { @class = "form-control", placeholder = "Image Tooltip" } })
                        @Html.ValidationMessageFor(model => model.EventImageTooltip, "", new { @class = "text-danger" })
                    </div>
                </div>
            
            
                <div class="form-group">
                    @Html.LabelFor(x => x.ContactPerson, "Contact Person :", htmlAttributes: new { @class = "control-label col-md-2" })
                    <div class="col-md-10">
                        @Html.EditorFor(model => model.ContactPerson, new { htmlAttributes = new { @class = "form-control", placeholder = "Contact Person" } })
                        @Html.ValidationMessageFor(model => model.ContactPerson, "", new { @class = "text-danger" })
                    </div>
                </div>
            @*</div>*@
        @*<div class="col-lg-6">*@
            <div class="form-group">
                @Html.LabelFor(x => x.ContactEmailAddress, "Contact Email :", htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.ContactEmailAddress, new { htmlAttributes = new { @class = "form-control", placeholder = "Contact Email" } })
                    @Html.ValidationMessageFor(model => model.ContactEmailAddress, "", new { @class = "text-danger" })
                </div>
            </div>

            <div class="form-group">
                @Html.LabelFor(x => x.FeedbackFieldShow, "Feedback Field :", htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    <div class="checkbox">
                        @Html.EditorFor(model => model.FeedbackFieldShow)
                        @Html.ValidationMessageFor(model => model.FeedbackFieldShow, "", new { @class = "text-danger" })
                    </div>
                </div>
            </div>

            <div class="form-group">
                @Html.LabelFor(x => x.VolunteerReqFieldShow, "Volunteer Field :", htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    <div class="checkbox">
                        @Html.EditorFor(model => model.VolunteerReqFieldShow)
                        @Html.ValidationMessageFor(model => model.VolunteerReqFieldShow, "", new { @class = "text-danger" })
                    </div>
                </div>
            </div>

            <div class="form-group">
                @Html.LabelFor(x => x.IsPublished, "Published :", htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    <div class="checkbox">
                        @Html.EditorFor(model => model.IsPublished)
                        @Html.ValidationMessageFor(model => model.IsPublished, "", new { @class = "text-danger" })
                    </div>
                </div>
            </div>

            <div class="form-group">
                @Html.LabelFor(x => x.PublishedDate, "Published Date :", htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.PublishedDate, new { htmlAttributes = new { @class = "form-control", placeholder = "Published Date" } })
                    @Html.ValidationMessageFor(model => model.PublishedDate, "", new { @class = "text-danger" })
                </div>
            </div>

            @*<div class="form-group">
                @Html.LabelFor(model => model.EventDetailsId, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.EventDetailsId, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.EventDetailsId, "", new { @class = "text-danger" })
                </div>
            </div>*@

            <div class="form-group">
                @Html.LabelFor(x => x.AdultsFieldShow, "Adults Field :", htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    <div class="checkbox">
                        @Html.EditorFor(model => model.AdultsFieldShow)
                        @Html.ValidationMessageFor(model => model.AdultsFieldShow, "", new { @class = "text-danger" })
                    </div>
                </div>
            </div>

            <div class="form-group">
                @Html.LabelFor(x => x.ToddlersFieldShow, "Toddlers Field :", htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    <div class="checkbox">
                        @Html.EditorFor(model => model.ToddlersFieldShow)
                        @Html.ValidationMessageFor(model => model.ToddlersFieldShow, "", new { @class = "text-danger" })
                    </div>
                </div>
            </div>

            <div class="form-group">
                @Html.LabelFor(x => x.GenderFieldShow, "Gender Field :", htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    <div class="checkbox">
                        @Html.EditorFor(model => model.GenderFieldShow)
                        @Html.ValidationMessageFor(model => model.GenderFieldShow, "", new { @class = "text-danger" })
                    </div>
                </div>
            </div>

            <div class="form-group">
                @Html.LabelFor(x => x.FoodFieldShow, "Food Field :", htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    <div class="checkbox">
                        @Html.EditorFor(model => model.FoodFieldShow)
                        @Html.ValidationMessageFor(model => model.FoodFieldShow, "", new { @class = "text-danger" })
                    </div>
                </div>
            </div>

            <div class="form-group">
                @Html.LabelFor(x => x.AlcoholicsFieldShow, "Alcoholics Field :", htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    <div class="checkbox">
                        @Html.EditorFor(model => model.AlcoholicsFieldShow)
                        @Html.ValidationMessageFor(model => model.AlcoholicsFieldShow, "", new { @class = "text-danger" })
                    </div>
                </div>
            </div>

            <div class="form-group">
                @Html.LabelFor(x => x.TransportReqFieldShow, "Transport Field :", htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    <div class="checkbox">
                        @Html.EditorFor(model => model.TransportReqFieldShow)
                        @Html.ValidationMessageFor(model => model.TransportReqFieldShow, "", new { @class = "text-danger" })
                    </div>
                </div>
            </div>

            <div class="form-group">
                @Html.LabelFor(x => x.AlertsReqFieldShow, "Alerts Field :", htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    <div class="checkbox">
                        @Html.EditorFor(model => model.AlertsReqFieldShow)
                        @Html.ValidationMessageFor(model => model.AlertsReqFieldShow, "", new { @class = "text-danger" })
                    </div>
                </div>
            </div>
        @*</div>*@
        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Create" class="btn btn-default" />
                &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
                &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
                <input type="submit" value="Preview" class="btn btn-default" /> 
             </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("View All Events", "Index")
</div>

EventsEngineering/EventsEngineering/Views/EventData/Delete.cshtml
@model EventsEngineering.DTO.EventData

@{
    ViewBag.Title = "Delete";
}

<h2>Delete</h2>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>EventData</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.EventName)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.EventName)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.EventDescription)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.EventDescription)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.EventDate)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.EventDate)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Venue)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Venue)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.VenueURL)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.VenueURL)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.VenueImage)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.VenueImage)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.VenueLocationImage)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.VenueLocationImage)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.EventImage)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.EventImage)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.EventImageTooltip)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.EventImageTooltip)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.ContactPerson)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.ContactPerson)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.ContactEmailAddress)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.ContactEmailAddress)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.FeedbackFieldShow)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.FeedbackFieldShow)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.VolunteerReqFieldShow)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.VolunteerReqFieldShow)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.IsPublished)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.IsPublished)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.PublishedDate)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.PublishedDate)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.EventDetailsId)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.EventDetailsId)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.AdultsFieldShow)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.AdultsFieldShow)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.ToddlersFieldShow)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.ToddlersFieldShow)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.GenderFieldShow)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.GenderFieldShow)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.FoodFieldShow)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.FoodFieldShow)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.AlcoholicsFieldShow)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.AlcoholicsFieldShow)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.TransportReqFieldShow)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.TransportReqFieldShow)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.AlertsReqFieldShow)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.AlertsReqFieldShow)
        </dd>

    </dl>

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Delete" class="btn btn-default" /> |
            @Html.ActionLink("Back to List", "Index")
        </div>
    }
</div>

EventsEngineering/EventsEngineering/Views/EventData/Details.cshtml
@model EventsEngineering.DTO.EventData

@{
    ViewBag.Title = "Details";
}

<h2>Details</h2>

<div>
    <h4>EventData</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.EventName)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.EventName)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.EventDescription)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.EventDescription)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.EventDate)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.EventDate)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Venue)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Venue)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.VenueURL)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.VenueURL)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.VenueImage)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.VenueImage)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.VenueLocationImage)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.VenueLocationImage)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.EventImage)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.EventImage)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.EventImageTooltip)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.EventImageTooltip)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.ContactPerson)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.ContactPerson)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.ContactEmailAddress)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.ContactEmailAddress)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.FeedbackFieldShow)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.FeedbackFieldShow)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.VolunteerReqFieldShow)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.VolunteerReqFieldShow)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.IsPublished)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.IsPublished)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.PublishedDate)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.PublishedDate)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.EventDetailsId)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.EventDetailsId)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.AdultsFieldShow)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.AdultsFieldShow)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.ToddlersFieldShow)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.ToddlersFieldShow)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.GenderFieldShow)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.GenderFieldShow)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.FoodFieldShow)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.FoodFieldShow)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.AlcoholicsFieldShow)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.AlcoholicsFieldShow)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.TransportReqFieldShow)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.TransportReqFieldShow)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.AlertsReqFieldShow)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.AlertsReqFieldShow)
        </dd>

    </dl>
</div>
<p>
    @Html.ActionLink("Edit", "Edit", new { id = Model.EventId }) |
    @Html.ActionLink("Back to List", "Index")
</p>

EventsEngineering/EventsEngineering/Views/EventData/Index.cshtml
@model IEnumerable<EventsEngineering.DTO.EventData>

@{
    ViewBag.Title = "Index";
}

<h2>Events</h2>

@*<p>
    @Html.ActionLink("Create New", "Create")
</p>*@
<table width ="100%"class="table">
   
    <tr>
        @foreach (var item in Model)
        {
            <td>
                <ul>
                    <li>
                        @Html.DisplayNameFor(model => model.EventName): @Html.DisplayFor(modelItem => item.EventName)
                    </li>
                    <li>
                        @Html.DisplayNameFor(model => model.EventDescription): @Html.DisplayFor(modelItem => item.EventDescription)
                    </li>
                    <li>
                        @Html.DisplayNameFor(model => model.EventDate): @Html.DisplayFor(modelItem => item.EventDate)
                    </li>
                    <li>
                        @Html.DisplayNameFor(model => model.Venue): @Html.DisplayFor(modelItem => item.Venue)
                    </li>
                    <li>
                        @Html.DisplayNameFor(model => model.VenueURL): @Html.DisplayFor(modelItem => item.VenueURL)
                    </li>

                    <li>
                        
                        @Html.DisplayNameFor(model => model.VenueImage)
                    </li>
                    <li>
                        <img src="../../images/@Html.DisplayFor(modelItem => item.VenueImage)" style="width:150px;height:150px;"/>
                    </li>
                    <li>
                        @Html.DisplayNameFor(model => model.VenueLocationImage)
                    </li>
                    <li>
                        @*@Html.DisplayNameFor(model => model.VenueLocationImage): @Html.DisplayFor(modelItem => item.VenueLocationImage)*@
                        <img src="../../images/@Html.DisplayFor(modelItem => item.VenueLocationImage)" style="width:150px;height:150px;" />
                    </li>
                    <li>
                        @Html.DisplayNameFor(model => model.EventImage)
                    </li>
                    <li>
                        @*@Html.DisplayNameFor(model => model.EventImage): @Html.DisplayFor(modelItem => item.EventImage)*@
                        <img src="../../images/@Html.DisplayFor(modelItem => item.EventImage)" style="width:150px;height:150px;" />
                    </li>
                    <li>
                        @Html.DisplayNameFor(model => model.EventImageTooltip): @Html.DisplayFor(modelItem => item.EventImageTooltip)
                    </li>
                    <li>
                        @Html.DisplayNameFor(model => model.ContactPerson): @Html.DisplayFor(modelItem => item.ContactPerson)
                    </li>
                    <li>
                        @Html.DisplayNameFor(model => model.ContactEmailAddress): @Html.DisplayFor(modelItem => item.ContactEmailAddress)
                    </li>

                    @if (Convert.ToString(Session["Is_Admin"]) == "admin")
                     {
                        <li>

                            @Html.ActionLink("Edit", "Edit", new { id = item.EventId }) |
                            @Html.ActionLink("Details", "Details", new { id = item.EventId }) |
                            @Html.ActionLink("Delete", "Delete", new { id = item.EventId })
                        </li>
                    }
                </ul>
            </td>
        }
    </tr>
</table>